### ISSUE TITLE
economic-order-quantity.ipynb

### ISSUE THREAD

**Issue by alessandrozocca** [mobook/MO-book#41]
- [x] Postpone bibliographic notes rather than having them at the top? 
- [x] Typo: "incorrectly cited ince 1931"
- [x] Add the URL for Ziegler paper, that is https://www.sciencedirect.com/science/article/abs/pii/016763778290030X 
- [x] Unclear sentence: "The problem is to find the size of a that minimizes the cost of maintaining that item in an inventory". In the book I rephrased it as "The problem consists of finding the order quantity that minimizes the cost of maintaining a specific item in inventory"
- [x] Typo: "given given"
- [x] Typo: "where $x$ is the...?"
- [x] Typo: "is define"
- [x] Unclear sentence "As the following diagrams the solution to this optimization problem."
- [x] Remove label/description on top of the 2nd figure (but maybe only when @gromicho gets here with figure regeneration)
- [x] Typo: "...the hyperbola described by the constraint $x y \leq 1$" should be $x y \geq 1$?
- [x] Too much white space around the Lorentz cone picture, needs to be trimmed (but maybe only when @gromicho gets here with figure regeneration)
- [x] "Note the improvement in accuracy of this calculation compared to the analytical solution." --> compared to the previous implementations?

**Comment by jckantor** [comment]
Thanks for the careful read. Much improved!
