### ISSUE TITLE
Add more examples in the style guide

### ISSUE THREAD

**Issue by leonlan** [mobook/MO-book#48]
Some sections in the style guide have a lot of examples:

https://github.com/mobook/MO-book/blob/a0f0f8f0e789746b29a85f41a48a9eba727254d0/pyomo_style_guide.md?plain=1#L110-L153

It would be nice to add more examples in some of the sections that currently have none, e.g.:

https://github.com/mobook/MO-book/blob/a0f0f8f0e789746b29a85f41a48a9eba727254d0/pyomo_style_guide.md?plain=1#L80-L105

**Comment by alessandrozocca** [comment]
Code snippets added to the Pyomo style guide.
