### ISSUE TITLE
Simplify Alice's rose example

### ISSUE THREAD

**Issue by leonlan** [mobook/MO-book#50]
https://github.com/mobook/MO-book/blob/main/notebooks/01/alice-rose.ipynb

Alice's rose example is overly complicated, involving symbolic math, $\pi$ stuff, Fermat's stuff...

I think it could all be reduced just to the mathematical optimization problem (starting from the pyomo model)

**Comment by alessandrozocca** [comment]
Notebook is now included again but in a much more simplified and streamlined version.
