### ISSUE TITLE
Add support for HiGHS solver

### ISSUE THREAD

**Issue by leonlan** [mobook/MO-book#53]
[HiGHS](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwi-uJCcv9X7AhUpM-wKHZmXCbcQFnoECBAQAQ&url=https%3A%2F%2Fgithub.com%2FERGO-Code%2FHiGHS&usg=AOvVaw3aEYwdkBFE5kjgs6MRaPXe) is a new open-source, high-performance solver for MILPs. It would be nice to add support for the HiGHS solver installation.

HiGHS has been recently added to PyPi, and there's now also an [interface](https://github.com/Pyomo/pyomo/pull/2561/files) with Pyomo. I haven't tried it yet, but I think it could be as simple as `pip install highspy` and then selecting `'highs'` in the solver interface.

**Comment by jckantor** [comment]
Completely agree, and this could take the place of cbc and glpk for the MILP and LP examples throughout the notebooks.  I've started using HIGHS myself.  By default it is a persistent solver, which we don't use enough in the examples.

The place for this fix is in helper.py. The issue I've been having is how to test for a prior install of HIGHS. The current test doesn't seem to work, not sure why HIGHS doesn't add itself to the path automatically, In any event, that part of helper.py is a kluge anyway.  So I'd like to replace that test with the Pyomo available solver test, then add HIGHS.

**Comment by jckantor** [comment]
Hi Leon,

I've added Highs as the "default" for many of the notebooks.  The key is to select the "appsi_highs" solver after install highspy. It's working very well.  It also appears to work when highspy is installed "over" idaes-pse, but I haven't tested that enough to be confident recommending that for every case.

I'll close this for now. Feel free to reopen if you have some thoughts.

Jeff
