### ISSUE TITLE
About milk pooling model with IPOPT

### ISSUE THREAD

**Issue by rlacjfjin** [mobook/MO-book#54]
Hi,
In pooling problem using IPOPT solver, it may be found a local optimum, and how can I avoid falling into local optimum？
I think besides tuning some parameters of ipopt solver, it's also important how choose a starting point(solution), right? If so, can you give some advices about how to choose a "good" initial solution? 
In other aspect, I find it is also can use SLP(sequential linear programming) solve pooling problem(especially bilinear programming), such as aspen-pims which contains Distributive Recursion or SLP which call FICO-Xpress solver because of the specialize of the problem.
How about compare IPOPT with solve problem directly and solve the problem using successively process(such as SLP)?

Thanks,
Zhe.

**Comment by rlacjfjin** [comment]
Thanks.
And I have confused:
I write the problem as milk_pooling.nl, but pyomo seems can't support read file, right?
If I want to create a problem from reading a file(such as lp,mps,nl and so on format), how to do it ?

Zhe.

**Comment by jckantor** [comment]
Zhe ... keep in mind that Pyomo is a modeling language, not a solver. It can produce a .nl file, and communicate with solvers using the .nl file, but doesn't require user to do anything.

Jeff

**Comment by rlacjfjin** [comment]
> Zhe ... keep in mind that Pyomo is a modeling language, not a solver. It can produce a .nl file, and communicate with solvers using the .nl file, but doesn't require user to do anything.
> 
> Jeff

Thank you for the reminder, indeed I was confused....
