### ISSUE TITLE
Issue on page /notebooks/03/machine-scheduling.html

### ISSUE THREAD

**Issue by deRemo** [mobook/MO-book#55]
Hi, your companion notebooks are pretty useful!

A couple of suggestions regarding "Mixed-Integer Linear Optimization: Machine Scheduling"

- The Gantt charts should display a legend to explain the colors (I mean, you get that by looking at the code - but it shouldn't be required)
- Some grammar checks ("*[...] the time at which the job is released to the for machine processing*", "*[...]  sequence the jobs on the machine that meets the the due dates*"

**Comment by jckantor** [comment]
Thanks for the comment and suggestions.  These are very helpful.  I've made the suggested grammar changes, cleaned up the graphics and added a legend, and some other minor coding improvements. 

Feel free to reopen the issue if you have other suggestions.
