### ISSUE TITLE
Issue on page /notebooks/09/economicdispatch.html

### ISSUE THREAD

**Issue by BernardZweers** [mobook/MO-book#56]
Something seems to be going wrong with the first model formulation in section "MILO reformulation for the chance-constrained ED problem". I have the following screen 
![Screenshot_20230424_214056_Chrome](https://user-images.githubusercontent.com/101557341/234099619-e7edd903-a669-441e-b725-df2ee33d3b48.jpg)

**Comment by jckantor** [comment]
Thank you!  That was a math formatting error. It's been fixed and verified. Feel free to reopen if you if notice any similar issues in this or other notebooks.
