### ISSUE TITLE
Issue on page /notebooks/01/01.00.html

### ISSUE THREAD

**Issue by vinayrai12** [mobook/MO-book#58]
Hi ,
There seems to be a tiny error on chapter 1 , first page .. second last para starting with "Mathematically, we can describe optimization problems as follows" has an equation f(y) >= f(c) . I think it should be f(y) >= f(x) . ( or I might be completely wrong)

**Comment by jckantor** [comment]
Yes, thank you!  This is fixed and will be in the next commit to the repository.
