### ISSUE TITLE
Issue on page /notebooks/01/production-planning-basic.html

### ISSUE THREAD

**Issue by LittlePanther-Susie** [mobook/MO-book#62]
The table in the previous page (https://mobook.github.io/MO-book/notebooks/01/production-planning.html) and constraint functions in code do not match.

| Version | Raw Material <br> required | Labor A <br> required | Labor B <br> required | Market <br> Demand | Price |
| :-: | :-: | :-: | :-: | :-: | :-: | 
| U | 10 g | 1 hr | 2 hr | $\leq$ 40 units | 270€ |
| V |  9 g | 1 hr | 1 hr | unlimited | 210€ |

Current code
```
@model.Constraint()
def labor_A(model):
    return 2 * model.y_U + 1 * model.y_V <= model.x_A

@model.Constraint()
def labor_B(model):
    return 1 * model.y_U + 1 * model.y_V <= model.x_B
```

Update
```
@model.Constraint()
def labor_A(model):
  return 1 * model.y_U + 1 * model.y_V <= model.x_A

@model.Constraint()
def labor_B(model):
  return 2 * model.y_U + 1 * model.y_V <= model.x_B
```

**Comment by jckantor** [comment]
Thanks, Susie. This was an error in transcribing details of a model to the notebook, and actually propagated through all three notebooks associated with Chapter 1 of the project. Thanks for pointing this one out!  Corrections have been made, answers verified, so issue will be closed.
