### ISSUE TITLE
Issue on page /notebooks/02/bim-rawmaterialplanning.html

### ISSUE THREAD

**Issue by AndresFCortes** [mobook/MO-book#63]
The 'display' function is not called: from IPython.display import display

**Comment by jckantor** [comment]
Hi Andreas.  Thanks for the raising the issue.  I've been looking into adding the import statement, but wondering why you consider this necessary. I've checked a few Jupyter interfaces and find that they all load display from IPython.display automatically. Are encountering an issue with this?

Jeff

**Comment by jckantor** [comment]
The statement 

from IPython.display import display

has been added to explicitly specify the display function and dependency. The notebook has been updated for a consistent presentation and use of display.
