### ISSUE TITLE
Issue on page /notebooks/04/power-network.html

### ISSUE THREAD

**Issue by nfbvs** [mobook/MO-book#65]
- Issues with objective sense:
In the 'Optimal Power Flow' section the problem is stated as a maximization problem.
In the 'Solving OPF' section the problem is declared as a minimization problem but implemented as a maximization one.
- Potential typo in OPF2:
`def generation_upperound(m, i):` should probably be `def generation_upper_bound(m, i):`
- Docstring of OPF functions:
docstring mentions the return of two dictionaries but the functions are returning the objective

Probably also relevant: in nodes.csv the first (nameless) column is a duplicate of the `node_id` column. This column is used as an index, but has duplicated values.

**Comment by alessandrozocca** [comment]
Thank you for catching all these typos and inconsistencies. The latest commit fixes them. 

The .csv file is indeed imported with a dubious choice for the index, but I believe it doesn't cause any issues in the notebook.
