### ISSUE TITLE
Issue on page /notebooks/02/05-bim-fractional.html

### ISSUE THREAD

**Issue by smu095** [mobook/MO-book#83]
In the section describing the fractional objective, should the constraint

$\frac{7}{6}y_{1} + \frac{5}{6}y_{2} + 100y = 1$

be changed to

$\frac{7}{6}y_{1} + \frac{5}{6}y_{2} + 100t = 1$?

**Comment by alessandrozocca** [comment]
Thanks for spotting the typo, the latest commit fixes it.
